### ISSUE TITLE
Breaking changes not released as a new major version

### ISSUE THREAD

**Issue by DennisL68** [luigilink/SPSWakeUp#17]
I noticed that v2.7.2 contains breaking changes. A common practice is to increase the major version (i.e. go to v3.x in this case) to clearly communicate that the new version will break old configurations if used in the same manner as the previous version.

**Comment by luigilink** [comment]
Thanks for this advice.

**Comment by luigilink** [comment]
Fixed in release 3.0.1 @DennisL68 
Thanks again for this issue ;)
